name: Home Meters CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      working-directory: ./app
      run: lein deps
    - name: Run tests
      working-directory: ./app
      run: lein test

# include ui tests 
